config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :gnarlies
  resources :welcome, only: [:index]
  resources :sessions, only: [:new, :create, :destroy]
  # resources :gnarly, only: [:create, :new, :index, :show, :destroy]
  get '/login', to: 'sessions#new'
  get '/gnarlies/:id/like', to: 'gnarlies#like', as: :like
end

app/models/gnarly.rb
class Gnarly < ActiveRecord::Base
  belongs_to :user
  before_save :default_values

  def default_values
    self.likes ||= 0
  end
end

app/models/user.rb
class User < ActiveRecord::Base
 has_many :gnarlies

 has_secure_password
 # Verify that an email exists and that it does not already exist in the db
 validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   private

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
      redirect_to login_path, alert: 'Not authorized - you must be logged in!' if current_user.nil?
  end
end

app/controllers/gnarlies_controller.rb
class GnarliesController < ApplicationController
  before_action :authenticate,      only: [:create, :destroy]
  before_action :authorize_create,  only: [:create]

  def index
    @gnarlies = Gnarly.all
  end
  def new
    @gnarlie = Gnarly.new
  end

  def show
    @gnarlie = Gnarly.find(params[:id])
  end

  # nested route /users/:user_id/gnarlies
  def create
    @gnarlie = Gnarly.new(gnarlie_params)
    @gnarlie.user = current_user

    if @gnarlie.save
      flash[:notice] = "You're freakin Gnarly!"
      redirect_to user_path(current_user)
    else
      render 'new'
    end
  end

  def destroy
    gnarly = Gnarly.find(params[:id])
    gnarly.destroy
    redirect_to user_path(current_user)
  end

  def like
    gnarly = Gnarly.find(params[:id])
    gnarly.likes += 1
    gnarly.save
    redirect_to root_path
  end

  private

    def gnarlie_params
      params.require(:gnarly).permit(:text, :image_uri)
    end

    def authenticate
      redirect_to new_session_path, alert: 'You must be logged in to continue!' if current_user.nil?
    end

    # nested route /users/:id/gnarlies
def authorize_create
      @user = User.find(session[:user_id])
      redirect_to root_path if @user != current_user
    end

    def authorize_destroy
      @gnarlie = Gnarly.find(params[:id])
      redirect_to root_path if @mumble.user != current_user
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

    def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in!'
    else
      flash.now.alert = 'Invalid login credentials - try again!'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate, only: [:show, :edit, :update]
  before_action :authorize, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You have successfully signed up!"
      session[:user_id] = @user.id # login
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @gnarlies = current_user.gnarlies
  end

  def edit
    @user = User.find(params[:id]) # being done in authorize
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private
    # Implement Strong Params
    def user_params
      params.require(:user).permit(:name, :username, :email, :password)
    end

    def authenticate
      redirect_to new_session_path, alert: 'You must be logged in to continue!' if current_user.nil?
    end

    def authorize
      @user = User.find(params[:id])
      redirect_to root_path if @user != current_user
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @gnarlies = Gnarly.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gnarlies/_gnarlie.html.erb
<div class="container">
<div class="form-signin">
<section class="gnarly-pic">
  <%= form_for @gnarlie do |f| %>
    <div class="field">
      <%= f.label :text %>
      <%= f.text_field :text, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :image_uri %>
      <%= f.text_field :image_uri, class: 'form-control' %>
    </div>
    <br>
    <div class="actions"><%= f.submit "Rad!" %></div>
  <% end %>
</section>
</div>
</div>

app/views/gnarlies/gnarlie.html.erb
<section class="gnarly-pic">
 <p><%= @gnarlie.text %></p>
 <%= image_tag @gnarlie.image, class: "gnarly-pic" %>
 <%= button_to "Tubular!", edit_gnarlie_path(@gnarlie), method: :get %>
</section>

app/views/gnarlies/index.html.erb
<% @gnarlies.order(id: :desc).each do |gnarlie| %>
  <section class="gnarly-pic">
   <p><%= gnarlie.text %></p>
   <p><%= gnarlie.created_at %></p>
   <%= image_tag gnarlie.image_uri, class: "gnarly-pic" %>
   <%= button_to "Tubular!", edit_gnarly_path(gnarlie), method: :get %>
  </section>
<% end %>

app/views/gnarlies/new.html.erb
<%= render 'gnarlie' %>

app/views/gnarlies/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<%= render 'gnarlie', gnarlie: @gnarlie %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gnarly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <nav class="navbar navbar-inverse">
      <%= link_to "Home", root_path, :class=>"btn btn-primary" %>
      &nbsp;&nbsp;|&nbsp;&nbsp;
      <% if current_user %>
        <%= link_to "Profile", user_path(current_user), :class=>"btn btn-primary" %>
        &nbsp;&nbsp;|&nbsp;&nbsp;
        <%= link_to 'Log out of account', session_path('FU'), :class=>"btn btn-primary", method: :delete %>
      <% else %>
        <%= link_to "Create an account", new_user_path, :class=>"btn btn-primary" %>
        &nbsp;&nbsp;|&nbsp;&nbsp;
        <%= link_to "Log in to account", new_session_path, :class=>"btn btn-primary" %>
      <% end %>
  </nav>
</header>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<div class="container">
<div class="form-signin">
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :email, "Email" %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control'%>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <br>
  <div class="actions"><%= f.submit %></div>
<% end %>
</div>
</div>

app/views/users/edit.html.erb
<h1>Update your account details</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1 class="text-center">Register a new account</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="text-center">
<h1>Welcome <%= @user.name %></h1>

<p><%= @user.email %></p>

<%= button_to "Edit account", edit_user_path(@user), method: :get %>
<br>
<%= button_to "Create a Gnarly", new_gnarly_path, method: :get %>
</div>
<br>

<% @gnarlies.each do |g| %>
  <div class="gnarlie">
    <img src="<%= g.image_uri %>" width="350">
    <h3><%= g.text %></h3>
    <%= link_to " X ", gnarly_path(g), method: :delete%>
  </div>
  <br>
<% end %>

app/views/welcome/index.html.erb
<h1 class='text-center'>Get Gnarly</h1>
<% @gnarlies.each do |g| %>

  <div class="gnarlie">
    <h3><span><%= g.user.username %></span></h3>
    <img src="<%= g.image_uri %>" width="350">
    <h3><%= g.text %></h3>

       <p><%= g.created_at.strftime('%a %b %d') %></p>
    <%= link_to like_path(g) do %>
      <span class="glyphicon glyphicon-flash btn btn-xs btn-default"></span>
    <% end %>
    <span class="likes">&nbsp;&nbsp;<%= g.likes %></span>
  </div>
  <br>
<% end %>